export const CONTACT_EMAIL = 'anikhasan2@icloud.com'
export const CONTACT_PHONE = '01758409063'
export const CONTACT_ADDRESS = 'Bashundhara R/A, J Block, Road 20'
export const INSTAGRAM_URL = 'https://www.instagram.com/boilabin/'
export const FACEBOOK_URL = 'https://www.facebook.com/Boilabin'
