export const UI_ICON_ASSETS = {
  'arrow-left': '/assets/icons/ui/arrow-left.svg',
  'arrow-right': '/assets/icons/ui/arrow-right.svg',
  'bar-chart-2': '/assets/icons/ui/bar-chart-2.svg',
  cart: '/assets/icons/ui/cart.svg',
  check: '/assets/icons/ui/check.svg',
  'check-circle': '/assets/icons/ui/check-circle.svg',
  'chevron-down': '/assets/icons/ui/chevron-down.svg',
  'chevron-right': '/assets/icons/ui/chevron-right.svg',
  'chevron-up': '/assets/icons/ui/chevron-up.svg',
  close: '/assets/icons/ui/close.svg',
  compare: '/assets/icons/ui/compare.svg',
  'credit-card': '/assets/icons/ui/credit-card.svg',
  eye: '/assets/icons/ui/eye.svg',
  'eye-off': '/assets/icons/ui/eye-off.svg',
  filter: '/assets/icons/ui/filter.svg',
  grid: '/assets/icons/ui/grid.svg',
  'grid-3x3': '/assets/icons/ui/grid-3x3.svg',
  headphones: '/assets/icons/ui/headphones.svg',
  heart: '/assets/icons/ui/heart.svg',
  'heart-filled': '/assets/icons/ui/heart-filled.svg',
  'help-circle': '/assets/icons/ui/help-circle.svg',
  laptop: '/assets/icons/ui/laptop.svg',
  'layout-dashboard': '/assets/icons/ui/layout-dashboard.svg',
  'life-buoy': '/assets/icons/ui/life-buoy.svg',
  'log-out': '/assets/icons/ui/log-out.svg',
  location: '/assets/icons/ui/location.svg',
  mail: '/assets/icons/ui/mail.svg',
  menu: '/assets/icons/ui/menu.svg',
  minus: '/assets/icons/ui/minus.svg',
  package: '/assets/icons/ui/package.svg',
  phone: '/assets/icons/ui/phone.svg',
  plus: '/assets/icons/ui/plus.svg',
  'refresh-ccw': '/assets/icons/ui/refresh-ccw.svg',
  search: '/assets/icons/ui/search.svg',
  share: '/assets/icons/ui/share.svg',
  shield: '/assets/icons/ui/shield.svg',
  'shopping-bag': '/assets/icons/ui/shopping-bag.svg',
  'shopping-cart': '/assets/icons/ui/shopping-cart.svg',
  'sliders-horizontal': '/assets/icons/ui/sliders-horizontal.svg',
  sparkles: '/assets/icons/ui/sparkles.svg',
  star: '/assets/icons/ui/star.svg',
  'star-filled': '/assets/icons/ui/star-filled.svg',
  tag: '/assets/icons/ui/tag.svg',
  'trash-2': '/assets/icons/ui/trash-2.svg',
  truck: '/assets/icons/ui/truck.svg',
  user: '/assets/icons/ui/user.svg',
  watch: '/assets/icons/ui/watch.svg',
  x: '/assets/icons/ui/x.svg',
  zap: '/assets/icons/ui/zap.svg',
  'category-electronics': '/assets/icons/ui/categories/electronics.svg',
  'category-fashion': '/assets/icons/ui/categories/fashion.svg',
  'category-home-appliances': '/assets/icons/ui/categories/home-appliances.svg',
  'category-beauty-health': '/assets/icons/ui/categories/beauty-health.svg',
  'category-sports-fitness': '/assets/icons/ui/categories/sports-fitness.svg',
  'category-books-stationery': '/assets/icons/ui/categories/books-stationery.svg',
  'category-gaming': '/assets/icons/ui/categories/gaming.svg',
  'category-toys-collectibles': '/assets/icons/ui/categories/toys-collectibles.svg',
  'category-view-all': '/assets/icons/ui/categories/view-all.svg',
} as const

export const SOCIAL_ICON_ASSETS = {
  facebook: '/assets/icons/social/facebook.svg',
  instagram: '/assets/icons/social/instagram.svg',
  youtube: '/assets/icons/social/youtube.svg',
} as const

export const STOREFRONT_ICON_ASSETS = {
  ...UI_ICON_ASSETS,
  ...SOCIAL_ICON_ASSETS,
} as const

export type StorefrontIconName = keyof typeof STOREFRONT_ICON_ASSETS
