ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "buttonLabel" TEXT;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "buttonStyle" TEXT NOT NULL DEFAULT 'light';
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "textPosition" TEXT NOT NULL DEFAULT 'left';
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "textTone" TEXT NOT NULL DEFAULT 'light';
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "overlayStrength" TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "textShadow" BOOLEAN NOT NULL DEFAULT true;

UPDATE "Banner"
SET "startsAt" = NULL
WHERE "startsAt" <= TIMESTAMP '1971-01-02 00:00:00';

UPDATE "Banner"
SET "endsAt" = NULL
WHERE "endsAt" <= TIMESTAMP '1971-01-02 00:00:00';
